### ISSUE TITLE
Lua Script Error on Redis 3.2

### ISSUE THREAD

**Issue by icheishvili** [seomoz/qless#250]
After upgrading to Redis 3.2, this error ends up being a showstopper:

```
Redis::CommandError - ERR Error running script (call to f_3f9682e7ddb462dca8c60a26d5e88ac70c3a49e9): @user_script:925: @user_script: 925: Lua redis() command arguments must be strings or integers :
  redis (3.3.0) lib/redis/client.rb:121:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/redis.rb:42:in `block in call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/datastores.rb:111:in `block in wrap'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/method_tracer.rb:73:in `block in trace_execution_scoped'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/method_tracer.rb:71:in `trace_execution_scoped'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/datastores.rb:108:in `wrap'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/redis.rb:41:in `call'
  redis (3.3.0) lib/redis.rb:2394:in `block in _eval'
  redis (3.3.0) lib/redis.rb:58:in `block in synchronize'
  /Users/xxx/.rbenv/versions/2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  redis (3.3.0) lib/redis.rb:58:in `synchronize'
  redis (3.3.0) lib/redis.rb:2393:in `_eval'
  redis (3.3.0) lib/redis.rb:2445:in `evalsha'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless/lua_script.rb:44:in `_call'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless/lua_script.rb:26:in `block in call'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless/lua_script.rb:49:in `handle_no_script_error'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless/lua_script.rb:25:in `call'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless.rb:202:in `call'
   () Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/qless-e5615c39eaff/lib/qless/queue.rb:108:in `put'
```

Is this even a supported version?

**Comment by pdelanauze** [comment]
Maybe this issue should be logged in the qless-core repo where the lua script logic resides ?

**Comment by dlecocq** [comment]
Sorry to hear about this issue, but yes, please file under `qless-core`.

**Comment by icheishvili** [comment]
Closed here. Re-opened here: https://github.com/seomoz/qless-core/issues/63
